### ISSUE TITLE
Looking for stats no longer works

### ISSUE THREAD

**Issue by Nemi123** [fonsleenaars/tqdb#50]
I believe this new optimization thing about only rendering the stuff the user is looking at is the cause of this issue. I would normally ctrl + f on a certain item type page to find whatever stats I'm looking for, but now it gives 0 results most of the time because the item with those stats aren't being rendered. 

Example: go to the shields page, and type "reflect" in the ctrl + f search bar. I got 0 results, despite there being several shields that have this stat.

However, I can easily zoom out until every item is visible and then the search works just fine.

**Comment by fonsleenaars** [comment]
Yeah I ran into this myself while I was developing it. My solution for now is that the search bar at the top is also going to fuzzy search the stats soon.

The optimization kind of forces this behavior as it stands. I'll either find a balance between the two, or otherwise the top search bar will still have the desired functionality.

Thanks for reporting this, I forgot to do so myself while developing the optimized rendering list.

**Comment by fonsleenaars** [comment]
It's been deployed to production with a small release note for v1.2.7. I'll close this issue now but if there's further issues I'll re-open it.
