### ISSUE TITLE
Monster attack names don't match up with effects

### ISSUE THREAD

**Issue by Quanyails** [fonsleenaars/tqdb#55]
Hi, fonsleenaars! I first want to thank you again for this excellent resource. It's super-helpful in finding the right bosses to farm as well as how to most efficiently counter them.

I noticed on the Monsters list that the list of attack names don't match up with their effects. For instance, almost every monster has a "Frost Strike" skill as their basic attack. I'm also sure the infamous Banmaru doesn't use Flame Strike and Volcanic Orb, either. Any idea where this is coming from?

**Comment by fonsleenaars** [comment]
Glad to hear it!

Indeed, it's quite peculiar but apparently "Frost Strike" is used as the name for a LOT of "default attacks" or "unnamed skills". The reason for this seems that there was just never a name assigned to the skill because there's nowhere for the name to appear, so it defaults to this "silly" name. 

Unfortunately, because it IS a tag in the game, I don't quite have a way of detecting which are real "frost strikes" and which are fake

**Comment by fonsleenaars** [comment]
Closing this because I'm afraid there's not much I could do about it :(
