### ISSUE TITLE
Titan Quest: Atlantis support?

### ISSUE THREAD

**Issue by chefranov** [fonsleenaars/tqdb#58]
Today realised new expansion https://steamcommunity.com/games/475150/announcements/detail/1601504362724611319
Will you support this expansion?

**Comment by fonsleenaars** [comment]
Wow, cool! I haven't had a lot of time for any personal project since I've started my new job but I definitely want to support it.

If I can find any fraction of time this weekend I'll buy it and run the parser with it.

**Comment by fonsleenaars** [comment]
I bought the expansion and ran the parser, it crashed halfway through so I'll be debugging what's going wrong there.

**Comment by chefranov** [comment]
if you have time don't forget about my errors in the neighbor topic

**Comment by fonsleenaars** [comment]
Yeah sorry about that, if I have any time left I'll try to see where I left off. Busy busy :(

**Comment by fonsleenaars** [comment]
I've got most of the stuff parsed already, it seems there are some bugs with the new necklaces and rings because almost all of them have no properties:

![image](https://user-images.githubusercontent.com/4301261/57585004-13fe2680-74b0-11e9-97be-789fc7994c12.png)

I'll have to run over the data and see what else is missing. Afterwards I have a few patches waiting for the website, including full locale/language support, so I'll push everything as soon as it looks releasable!

Don't think I'll get to your other issue this weekend, sorry.

**Comment by chefranov** [comment]
Okay! We will wait for new features on your site

**Comment by fonsleenaars** [comment]
It's been deployed to tq-db.net.

**Comment by chefranov** [comment]
Some Atlantis Items don't have Loot table :( https://tq-db.net/equipment/%D0%B1%D0%BE%D0%B5%D0%B2%D0%B0%D1%8F-%D0%BA%D0%BE%D1%80%D0%BE%D0%BD%D0%B0-%D0%B4%D0%B0%D0%BD%D0%B0%D1%8F

**Comment by fonsleenaars** [comment]
Indeed, as I mentioned in the release notes, I have not yet parsed the new bosses and such, these will follow in an update :)
