### ISSUE TITLE
Missing monster infrequents beginning with "Outlaw's"

### ISSUE THREAD

**Issue by Sir-Mac** [fonsleenaars/tqdb#74]
Hi, Fons Leenaars,

I have another information for you about missing gear in your database. In Ragnarök, there are monster infrequent items (coloured in olive green), with their respective names. As always, I give you the clue, hint from the locale file, x2uniqueequipment.txt.

x2tagMIWeapon033={^l}Outlaw's Buckler
x2tagMIArmor047={^l}Outlaw's Skullcap
x2tagMIArmor048={^l}Outlaw's Tunic

It is possible, that the items have no stats, I can't tell you. But I ask you to check it out as all the other issues, which I pointed out. I would like to have your database most comprehensive as possible.

Sir-Mac

**Comment by fonsleenaars** [comment]
@Sir-Mac I checked the database, there are no records for these files from what I can see, that means although the names were pre-allocated, they never made it into the release.

As an example, I found the item right before and after the buckler (032, 034) but not the buckler (033)

```
equipmentweapons/bow/mi_l_fjordmelee.dbr:310:itemNameTag,x2tagMIWeapon032,
equipmentweapons/staff/mi_e_fjordmage.dbr:315:itemNameTag,x2tagMIWeapon034,
```

Same for the Skullcap and Tunic

Thanks for reporting, I'm going to close this since it appears these items just aren't in the game!
