### ISSUE TITLE
Hood of the chosen, values

### ISSUE THREAD

**Issue by ghost** [fonsleenaars/tqdb#84]
Hello
just noticing that Hood of the Chosen has messed values for "chance of recharge",
![hood of the chosen tqdb](https://user-images.githubusercontent.com/57844300/68998250-02a33600-08a8-11ea-806c-d225e8a03dc9.PNG)

**Comment by fonsleenaars** [comment]
Nice find! I'm pretty busy at the moment but I have 2 weeks off around Christmas & New Year's time, I'll probably try to clean up some bugs then.

Thanks for reporting it.

**Comment by Dlagon** [comment]
That's appreciated, thanks also for the fast reply. Keep up the good work

**Comment by rehevkor5** [comment]
Far as I can tell, this is correct, based on the contents of the files produced by ARZExtractor.exe.

Relevant files:
- Normal: `data/database/records/xpack2/item/equipmentarmor/helm/mi_n_nerthusshaman.dbr`
  `skillCooldownReductionChance,66.000000,`
- Epic: `data/database/records/xpack2/item/equipmentarmor/helm/mi_e_nerthusshaman.dbr`
  `skillCooldownReductionChance,44.000000,`
- Legendary: `data/database/records/xpack2/item/equipmentarmor/helm/mi_l_nerthusshaman.dbr`
  `skillCooldownReductionChance,55.000000,`

Does it appear any differently in the game?

**Comment by fonsleenaars** [comment]
Thanks for looking into that @rehevkor5 - if that's what the database lists, then that would indeed be what the game shows too. Must be an error on their side.

I'll close for now because there's nothing else we can do, I'll file the bug on their bugtracker and when they update it, I'll get notified and I'll update the DB.
